name: build
on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches: [ "main" ]

jobs:
  PHP-74:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build 7.4 FPM
        uses: docker/build-push-action@v5
        with:
          context: '7.4'
          push: true
          tags: closehandle/php:7.4-fpm-alpine

  PHP-82:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build 8.2 FPM
        uses: docker/build-push-action@v5
        with:
          context: '8.2'
          push: true
          tags: closehandle/php:8.2-fpm-alpine

  PHP-83:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build 8.3 FPM
        uses: docker/build-push-action@v5
        with:
          context: '8.3'
          push: true
          tags: closehandle/php:8.3-fpm-alpine
