name: build
on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build 7.4 FPM
        uses: docker/build-push-action@v4
        with:
          context: '7.4'
          push: true
          tags: closehandle/php:7.4-fpm-alpine

      - name: Build 8.2 FPM
        uses: docker/build-push-action@v4
        with:
          context: '8.2'
          push: true
          tags: closehandle/php:7.4-fpm-alpine
